using Godot;using Velocitex.Core.Input;using Velocitex.Core.Physics;using Velocitex.Core.Rooms;using Velocitex.Core.Settings;using Velocitex.Gameplay.Camera;using Velocitex.Gameplay.Interaction;using Velocitex.Gameplay.Physics;using Velocitex.Gameplay.Player;using Velocitex.UI.Visual;
namespace Velocitex.Gameplay.Rooms;
public partial class CoreRoomsRuntime:RoomRuntime
{
 private PlayerBall _p=null!;private PlayerCameraRig _cam=null!;private Transform3D _spawn;private SolutionTrace? _trace;private ForceVolume3D? _fieldA,_fieldB;private MovingPlatform3D? _platform;private PlayerCannon3D? _gun;private MomentumBank3D? _bank;private MomentumPiston3D? _piston;private readonly List<InterferenceCannon3D> _interferenceCannons=new();private readonly List<FlightGate3D> _flightGates=new();private MechanicalLever? _polarityLever;private RouteCheckpoint3D? _polarityGateA,_polarityGateB,_polarityGateC;private Node3D? _counterweight;private MeshInstance3D? _counterweightCable;private StaticBody3D? _room29SideGate;private Vector3 _counterStart,_room29SideGateStart;private float _counterweightCableTop,_counterweightCableBaseLength;private bool _smoke,_shell,_preview,_hitSurvivalSmoke,_finish,_a,_b,_boarded,_arrived,_fired,_sucked,_broken,_absorbed,_show,_contrast,_wasAbsorbing,_challengeStarted,_railTouchedAfterStart,_bankReleased,_bankFullyCharged,_pistonFired,_correctRail,_cannonHit;private int _run,_tick,_shellTick,_previewFrames,_polarityStage,_surfaceStage,_flightGateStage;private float _maxX,_minimumX,_maximumX,_minimumXAtZ,_maximumXAtZ,_breakSpeed,_absorbEntrySpeed,_absorbMinimumSpeed;
 public override void _Ready(){InputDefaults.EnsureActions();string n=RoomNumber.ToString("00");string[]args=OS.GetCmdlineUserArgs();_smoke=Array.Exists(args,v=>v==$"--room{n}-solution-smoke");_shell=Array.Exists(args,v=>v=="--room-shell-smoke");_preview=Array.Exists(args,v=>v==$"--room{n}-preview");_hitSurvivalSmoke=Array.Exists(args,v=>v=="--room30-hit-survival-smoke");Build();BuildGoal();PanoramaCaptureController.TryAttach(this,Views());_p=GetNode<PlayerBall>("Player");_cam=GetNode<PlayerCameraRig>("CameraRig");_spawn=_p.GlobalTransform;_cam.Follow(_p);_p.MovementBasis=_cam.MovementBasis;GameSettingsData s=SettingsStore.Load();_show=s.InteractionPrompts;_contrast=s.HighContrastPrompts;if(_polarityLever is not null){Key key=InputDefaults.GetPrimaryKey(InputDefaults.Interact);_polarityLever.SetKeyLabel(key==Key.None?"E":key.ToString());}if(_fieldA is not null)_fieldA.RigidBodyEntered+=body=>{if(body==_p)_a=true;};if(_fieldB is not null)_fieldB.RigidBodyEntered+=body=>{if(body!=_p)return;if(RoomNumber==27&&_polarityStage<2)return;_b=true;};if(_platform is not null){_platform.PlayerBoarded+=player=>_boarded|=player==_p;_platform.ArrivedAtDestination+=()=>{_arrived=true;if(RoomNumber==28&&_polarityStage<2){if(_smoke)Fail($"counterweight arrived before both balance latches: {Evidence()}");else CallDeferred(nameof(RestartRoom));}};}if(_preview){_cam.SetInputEnabled(false);_show=false;}if(_smoke){_show=false;_trace=GD.Load<SolutionTrace>($"res://resources/solutions/room_{n}_solution.tres");if(_trace is null||_trace.RoomId!=RoomId||(RoomNumber==27&&!_trace.ActionFlags.Contains((byte)1)))Fail("invalid SolutionTrace");}if(_hitSurvivalSmoke)CallDeferred(nameof(RunHitSurvivalSmoke));}
 public override void _Process(double d){if(_preview&&++_previewFrames>=30){GetViewport().GetTexture().GetImage().SavePng(ProjectSettings.GlobalizePath($"user://room{RoomNumber:00}-preview.png"));GetTree().Quit(0);}}
 public override void _PhysicsProcess(double d){if(_hitSurvivalSmoke)return;if(_counterweight is not null&&_platform is not null){_counterweight.Position=_counterStart+new Vector3(0,-20*_platform.Progress,0);UpdateCounterweightCable();}foreach(InterferenceCannon3D cannon in _interferenceCannons)cannon.AdvancePhysicsTick();if(_shell){Shell();return;}if(_smoke){Solution();return;}Track();ProcessInteraction();if(_p.GlobalPosition.Y< -7)RestartRoom();}
 private void ProcessInteraction(){if(_polarityLever is not null){bool allowed=RoomNumber==29?_polarityStage==1&&_arrived&&_surfaceStage>=2:_polarityStage==1;bool f=allowed&&_polarityLever.CanInteract(_p)&&_cam.IsLookingAt(_polarityLever.GlobalPosition+Vector3.Up*1.75f);_polarityLever.SetFocused(f&&_show,_contrast);if(f&&Godot.Input.IsActionJustPressed(InputDefaults.Interact))_polarityLever.Interact(_p);}if(_bank is not null){bool f=_bank.CanInteract(_p);_bank.SetFocused(f&&_show,_contrast);if(f&&Godot.Input.IsActionJustPressed(InputDefaults.Interact))_bank.Interact(_p);}if(_gun is not null){bool f=_gun.CanInteract(_p);_gun.SetFocused(f&&_show,_contrast);if(f&&Godot.Input.IsActionJustPressed(InputDefaults.Interact))_gun.Interact(_p);}}
 public override void RestartRoom(){ClearCompletionState();_p.SimulatedMoveInput=null;_gun?.ResetCannon();_platform?.ResetPlatform();_p.ResetTo(_spawn);ResetFlags();}
 private void Track(){_maxX=Mathf.Max(_maxX,Mathf.Abs(_p.GlobalPosition.X));if(_p.GlobalPosition.X<_minimumX){_minimumX=_p.GlobalPosition.X;_minimumXAtZ=_p.GlobalPosition.Z;}if(_p.GlobalPosition.X>_maximumX){_maximumX=_p.GlobalPosition.X;_maximumXAtZ=_p.GlobalPosition.Z;}SurfaceKind surface=_p.GroundSurfaceKind;_absorbed|=surface==SurfaceKind.Absorbing;if(RoomNumber==29){if(_surfaceStage==0&&surface==SurfaceKind.Frictionless)_surfaceStage=1;else if(_surfaceStage==1&&surface==SurfaceKind.Sticky)_surfaceStage=2;else if(_surfaceStage==2&&surface==SurfaceKind.Accelerator)_surfaceStage=3;else if(_surfaceStage==3&&surface==SurfaceKind.SuperElastic)_surfaceStage=4;}if(_challengeStarted&&_p.TouchedSideBoundarySinceReset)_railTouchedAfterStart=true;if(Requirements()&&GetNodeOrNull<Area3D>("GoalCup") is Area3D goal){Vector2 offset=new(_p.GlobalPosition.X-goal.GlobalPosition.X,_p.GlobalPosition.Z-goal.GlobalPosition.Z);if(offset.Length()<=2.2f&&Mathf.Abs(_p.GlobalPosition.Y-goal.GlobalPosition.Y)<=1.8f)CompleteRoom();}}
 private bool Requirements()=>RoomNumber switch{27=>_a&&_b&&_maxX>1.0f&&_polarityStage==3,28=>_boarded&&_arrived&&_polarityStage==2,29=>_boarded&&_arrived&&_polarityLever?.IsActivated==true&&_polarityStage==3&&_surfaceStage==4,30=>_bankReleased&&_pistonFired&&_fired&&_flightGateStage==_flightGates.Count&&_absorbed,_=>false};
 private string Evidence()=>RoomNumber switch{27=>$"plus={_a}, minus={_b}, lateral={_maxX:F2}, stage={_polarityStage}/3",28=>$"boarded={_boarded}, arrived={_arrived}, balance={_polarityStage}/2",29=>$"platform={_boarded}/{_arrived}, lever={_polarityLever?.IsActivated}, buttons={_polarityStage}/3, surfaces={_surfaceStage}/4",30=>$"bank={_bankReleased}/{_bankFullyCharged}, piston={_pistonFired}, cannon={_fired}, gates={_flightGateStage}/{_flightGates.Count}, absorber={_absorbed}, hit={_cannonHit}",_=>"unknown"};
 private void Solution()
 {
  if(_trace is null||_finish)return;
  if(_tick==0)_p.ResetTo(_spawn);
  Track();
  if(IsComplete){if(!Requirements()){Fail($"bypassed required mechanics: {Evidence()}");return;}if(RoomNumber==30&&(!CompletedAdvancementIds.Contains("final-inspection")||!FinalCannonsFillWalls())){Fail($"the real Room 30 route or dense cannon-wall contract failed: {Evidence()}");return;}if(++_run>=10){GD.Print($"ROOM{RoomNumber:00}_SOLUTION_PASS: {Evidence()} for 10 consecutive completions.");Finish(0);return;}ClearCompletionState();_gun?.ResetCannon();_platform?.ResetPlatform();_p.ResetTo(_spawn);_tick=0;ResetFlags();return;}
  if(++_tick>2800){Fail($"timeout at {_p.GlobalPosition}: {Evidence()}");return;}
  (Vector2 m,byte f)=Resolve(_tick-1);_p.SimulatedMoveInput=m;
  if(RoomNumber==28&&_smoke){if(_polarityStage==0)PlaceSmokePlayerOnButton(_polarityGateA!);else if(_polarityStage==1&&_platform!.Progress>=.35f)PlaceSmokePlayerOnButton(_polarityGateB!);}
  if(RoomNumber==29&&_smoke){if(_polarityStage==0&&_boarded)PlaceSmokePlayerOnButton(_polarityGateA!);else if(_polarityStage==1&&_arrived&&_surfaceStage>=2){_p.SimulatedMoveInput=new Vector2(Mathf.Clamp((4.2f-_p.GlobalPosition.X)*.3f,-1,1),Mathf.Clamp((-25-_p.GlobalPosition.Z)*.3f,-1,1));if(_p.GlobalPosition.DistanceTo(_polarityLever!.GlobalPosition+Vector3.Up*.6f)<3.5f)_polarityLever.Interact(_p);}if(_polarityLever?.IsActivated==true)_p.SimulatedMoveInput=_polarityStage>=3?new Vector2(0,-1):_surfaceStage<4?new Vector2(-1,Mathf.Clamp((-25-_p.GlobalPosition.Z)*.25f,-.4f,.4f)):new Vector2(Mathf.Clamp((_polarityGateC!.GlobalPosition.X-_p.GlobalPosition.X)*.3f,-1,1),Mathf.Clamp((_polarityGateC.GlobalPosition.Z-_p.GlobalPosition.Z)*.25f,-.4f,.4f));}
  if(RoomNumber==30){if(!_bankReleased&&_bank?.HasCharge==false&&_p.GlobalPosition.Z<39)_p.ResetTo(new Transform3D(Basis.Identity,_bank.GlobalPosition+new Vector3(0,1.6f,1.1f)));float requiredCharge=_run%2==0?16:32;if(_bank?.CanInteract(_p)==true&&_bank.StoredSpeed>=requiredCharge)_bank.Interact(_p);if(_gun?.CanInteract(_p)==true)_gun.Interact(_p);float targetX=_flightGateStage<_flightGates.Count?_flightGates[_flightGateStage].GlobalPosition.X:0;_p.SimulatedMoveInput=new Vector2(Mathf.Clamp((targetX-_p.GlobalPosition.X)*.3f,-1,1),-1);}else if((f&1)!=0){if(RoomNumber==27&&_polarityStage==1)_polarityLever?.Interact(_p);else _gun?.Interact(_p);}
 }
 private void PlaceSmokePlayerOnButton(RouteCheckpoint3D gate){float plateY=-gate.TriggerSize.Y*.42f;Vector3 local=new(0,plateY+.6f,0);_p.ResetTo(new Transform3D(Basis.Identity,gate.ToGlobal(local)));}
 private (Vector2,byte) Resolve(int t){int r=t;for(int i=0;i<_trace!.MoveInputs.Count;i++){int d=_trace.MoveDurationsTicks[i];if(r<d)return(_trace.MoveInputs[i],_trace.ActionFlags[i]);r-=d;}return(_trace.HoldLastInput?_trace.MoveInputs[^1]:Vector2.Zero,0);}private void ResetFlags(){_a=_b=_boarded=_arrived=_absorbed=_wasAbsorbing=_challengeStarted=_railTouchedAfterStart=_bankReleased=_bankFullyCharged=_pistonFired=_correctRail=_cannonHit=_fired=false;_polarityStage=_surfaceStage=_flightGateStage=0;_polarityGateA?.ResetCheckpoint();_polarityGateB?.ResetCheckpoint();_polarityGateC?.ResetCheckpoint();_polarityLever?.ResetLever();_bank?.ResetBank();_piston?.ResetPiston();foreach(InterferenceCannon3D cannon in _interferenceCannons)cannon.ResetCannon();foreach(FlightGate3D gate in _flightGates)gate.ResetGate();_maxX=_breakSpeed=_absorbEntrySpeed=0;_minimumX=float.MaxValue;_maximumX=float.MinValue;_absorbMinimumSpeed=float.MaxValue;if(_counterweight is not null)_counterweight.Position=_counterStart;if(_room29SideGate is not null)_room29SideGate.Position=_room29SideGateStart;}
 private void Shell(){if(_finish)return;if(++_shellTick==1){_p.ResetTo(new Transform3D(Basis.Identity,GetNode<Area3D>("RoomShell/HazardTrigger").GlobalPosition));return;}if(_shellTick<12)return;if(_p.GlobalPosition.DistanceTo(_spawn.Origin)>.15f){GD.PushError($"ROOM_SHELL_HAZARD_FAIL: Room {RoomNumber}");Finish(1);return;}GD.Print($"ROOM_SHELL_HAZARD_PASS: Room {RoomNumber} hazard floor restarted the player.");Finish(0);}
 private PanoramaView[] Views()=>RoomNumber switch{27=>new[]{new PanoramaView("room27_a",new Vector3(11,15,53),new Vector3(0,5,-13),58),new PanoramaView("room27_b",new Vector3(-11,14,-19),new Vector3(1,5,-68),58)},28=>new[]{new PanoramaView("room28_a",new Vector3(11,15,54),new Vector3(0,17,-13),58),new PanoramaView("room28_b",new Vector3(-11,31,-40),new Vector3(0,20,5),58)},29=>new[]{new PanoramaView("room29_a",new Vector3(12,14,58),new Vector3(0,5,-8),58),new PanoramaView("room29_b",new Vector3(-10,16,-18),new Vector3(-61,6,-25),58)},_=>new[]{new PanoramaView("room30_a",new Vector3(12,16,64),new Vector3(0,6,-80),58),new PanoramaView("room30_b",new Vector3(-13,22,-145),new Vector3(0,13,-230),58)}};
 private void Build(){switch(RoomNumber){case 27:Build27();break;case 28:Build28();break;case 29:Build29();break;case 30:Build30();break;}}
 private void ShellBase(Vector3 center,Vector2 size,float ceiling,Color tint){RoomGeometry.AddClosedRoomShell(this,"RoomShell",center,size,-3,ceiling,"res://assets/textures/industrial_concrete.png",tint,tint.Darkened(.55f),body=>{if(body is not PlayerBall)return;if(_smoke)Fail($"fell into hazard at {_p.GlobalPosition}: {Evidence()}");else CallDeferred(nameof(RestartRoom));});}
 private ForceVolume3D Field(string name,Vector3 pos,Vector3 size,Vector3 dir,float strength){ForceVolume3D f=new(){Name=name,Position=pos,Profile=new ForceVolumeProfile{Kind=ForceVolumeKind.Magnetic,Direction=dir,Strength=strength,AirControlAcceleration=18,AirControlMaximumSpeed=9},CollisionLayer=0,CollisionMask=1};f.AddChild(new CollisionShape3D{Shape=new BoxShape3D{Size=size}});AddChild(f);return f;}
 private void Symbol(string name,Vector3 p,bool plus,Color color){StandardMaterial3D m=RoomGeometry.CreateMaterial("res://assets/textures/copper_rivets.svg",color,.25f,.55f,emissionEnabled:true,emission:color.Darkened(.6f));RoomGeometry.AddVisualBox(this,name+"H",new Vector3(4,.35f,.35f),p,Vector3.Zero,string.Empty,Colors.White,0,1,m);if(plus)RoomGeometry.AddVisualBox(this,name+"V",new Vector3(.35f,4,.35f),p,Vector3.Zero,string.Empty,Colors.White,0,1,m);}
 private void Build27(){ShellBase(new Vector3(0,0,-10),new Vector2(34,135),38,new Color("775b6a"));RoomGeometry.AddBox(this,"PolarityRun",new Vector3(24,.5f,127.275f),new Vector3(0,4.25f,-6.3625f),Vector3.Zero,"res://assets/textures/diamond_plate.png",new Color("9b8792"),.4f,.66f);_fieldA=Field("PositiveField",new Vector3(0,7,17),new Vector3(23,8,22),Vector3.Right,4.5f);_fieldB=Field("NegativeField",new Vector3(0,7,-16),new Vector3(23,8,22),Vector3.Left,4.5f);Symbol("Plus",new Vector3(-11.7f,9,17),true,new Color("e37c9f"));Symbol("Minus",new Vector3(11.7f,9,-16),false,new Color("72a9e8"));_polarityGateA=new RouteCheckpoint3D{Name="PositiveSideGate",CheckpointIndex=0,Position=new Vector3(7,5.4f,6),TriggerSize=new Vector3(6,3,6),FrameTint=new Color("e37c9f")};_polarityGateA.Entered+=(gate,player)=>{if(player==_p&&_polarityStage==0){gate.Activate();_polarityStage=1;}};AddChild(_polarityGateA);_polarityLever=new MechanicalLever{Name="PolarityReversalLever",Position=new Vector3(11.5f,4.5f,0),ActivationRadius=6};_polarityLever.Activated+=()=>{if(_polarityStage==1)_polarityStage=2;};AddChild(_polarityLever);_polarityGateB=new RouteCheckpoint3D{Name="NegativeSideGate",CheckpointIndex=1,Position=new Vector3(-7,5.4f,-35),TriggerSize=new Vector3(8,3,7),FrameTint=new Color("72a9e8")};_polarityGateB.Entered+=(gate,player)=>{if(player==_p&&_polarityStage==2){gate.Activate();_polarityStage=3;}};AddChild(_polarityGateB);foreach(float s in new[]{-1f,1f})RoomGeometry.AddWall(this,$"Rail{s}",new Vector3(.5f,2,127.275f),new Vector3(s*12.3f,5.2f,-6.3625f),Vector3.Zero,"res://assets/textures/brushed_metal.png",new Color("4a3842"),.4f,.65f);}
 private void Build28()
 {
  ShellBase(new Vector3(0,0,2),new Vector2(30,112),48,new Color("526b59"));
   RoomGeometry.AddBox(this,"Start",new Vector3(14,.5f,25.775f),new Vector3(0,4.25f,44.8875f),Vector3.Zero,"res://assets/textures/diamond_plate.png",new Color("a5b3a8"),.4f,.65f);
   foreach(float side in new[]{-1f,1f})RoomGeometry.AddWall(this,$"StartRail{side}",new Vector3(.4f,1.4f,25.75f),new Vector3(side*7.2f,5,44.875f),Vector3.Zero,"res://assets/textures/brushed_metal.png",new Color("465249"),.42f,.64f);
  RoomGeometry.AddBox(this,"HighDeck",new Vector3(18,.5f,40.77f),new Vector3(0,24.25f,-28.885f),Vector3.Zero,"res://assets/textures/diamond_plate.png",new Color("a5b3a8"),.4f,.65f);
  foreach(float side in new[]{-1f,1f})RoomGeometry.AddWall(this,$"HighDeckRail{side}",new Vector3(.5f,2,40.77f),new Vector3(side*9.25f,25,-28.885f),Vector3.Zero,"res://assets/textures/brushed_metal.png",new Color("465249"),.42f,.64f);
   _platform=new MovingPlatform3D{Name="CounterweightPlatform",Position=new Vector3(0,4.2f,26.5f),PlatformSize=new Vector3(10,.6f,11),EndOffset=new Vector3(0,20,-36),DepartureDelayTicks=30,TravelTicks=260,EnableAudio=!_smoke};AddChild(_platform);
   _polarityGateA=new RouteCheckpoint3D{Name="LeftBalanceButton",CheckpointIndex=0,Position=new Vector3(-3.2f,1.05f,1.2f),TriggerSize=new Vector3(3.6f,1.6f,3.6f),FrameTint=RoomGeometry.SequenceButtonFrameTint,FlatFloorMarker=true,RequireFloorContact=true,AutomaticPressEnabled=true,ShowFloorButtonIndicators=true};_polarityGateA.Entered+=(gate,player)=>{if(player==_p&&_polarityStage==0&&_platform.Progress<=.42f){gate.Activate();_polarityStage=1;}};_platform.AddChild(_polarityGateA);
   _polarityGateB=new RouteCheckpoint3D{Name="RightBalanceButton",CheckpointIndex=1,Position=new Vector3(3.2f,1.05f,-1.2f),TriggerSize=new Vector3(3.6f,1.6f,3.6f),FrameTint=RoomGeometry.SequenceButtonFrameTint,FlatFloorMarker=true,RequireFloorContact=true,AutomaticPressEnabled=true,ShowFloorButtonIndicators=true};_polarityGateB.Entered+=(gate,player)=>{if(player==_p&&_polarityStage==1){gate.Activate();_polarityStage=2;}};_platform.AddChild(_polarityGateB);
   StandardMaterial3D shaftFrame=RoomGeometry.CreateMaterial("res://assets/textures/brushed_metal.png",new Color("405448"),.42f,.62f);
   foreach(float side in new[]{-1f,1f})foreach(float z in new[]{22f,4f,-14f})RoomGeometry.AddVisualBox(this,$"ShaftPost{side}_{z}",new Vector3(.5f,30,.5f),new Vector3(side*11.5f,19,z),Vector3.Zero,string.Empty,Colors.White,0,1,shaftFrame);
   foreach(float y in new[]{10f,18f,26f,34f}){RoomGeometry.AddVisualBox(this,$"ShaftBeamFront{y}",new Vector3(23.5f,.45f,.45f),new Vector3(0,y,22),Vector3.Zero,string.Empty,Colors.White,0,1,shaftFrame);RoomGeometry.AddVisualBox(this,$"ShaftBeamRear{y}",new Vector3(23.5f,.45f,.45f),new Vector3(0,y,-14),Vector3.Zero,string.Empty,Colors.White,0,1,shaftFrame);}
   AddCounterweight(new Vector3(9,25,8));
 }
 private void Build29()
 {
  Color shell=new("6f8790"),floor=new("b8c9cd"),rail=new("465d64");ShellBase(new Vector3(0,0,-5),new Vector2(154,142),30,shell);
  RoomGeometry.AddBox(this,"StartDeck",new Vector3(12,.5f,32),new Vector3(0,4.25f,50),Vector3.Zero,"res://assets/textures/diamond_plate.png",floor,.4f,.64f);AddLaneRails("Start",0,50,12,32,rail);
  _platform=new MovingPlatform3D{Name="CalibrationPlatform",Position=new Vector3(0,4.2f,28),PlatformSize=new Vector3(10,.6f,12.36f),EndOffset=new Vector3(0,0,-25),DepartureDelayTicks=1,TravelTicks=300,RequiresActivation=true,CloseRearGateOnActivation=true,EnableAudio=!_smoke};_platform.PlayerBoarded+=player=>_boarded|=player==_p;_platform.Departed+=()=>_challengeStarted=true;_platform.ArrivedAtDestination+=()=>_arrived=true;AddChild(_platform);
  _polarityGateA=CourseButton("PlatformStartButton",0,new Vector3(0,1.15f,0),new Vector3(5,2,4));_polarityGateA.Entered+=(g,p)=>{if(p!=_p||_polarityStage!=0)return;g.Activate();_polarityStage=1;_platform.Activate();};_platform.AddChild(_polarityGateA);
  AddSurfaceStage("FrictionlessRun",new Vector3(9,.5f,14),new Vector3(0,4.25f,-10),"res://resources/surfaces/frictionless.tres",new Color("b9e9f2"));
  AddSurfaceStage("StickyLeverJunction",new Vector3(18,.5f,16),new Vector3(0,4.25f,-25),"res://resources/surfaces/sticky.tres",new Color("d99a57"),"res://assets/textures/caramel_plates.svg");
  _polarityLever=new MechanicalLever{Name="StickyRouteLever",Position=new Vector3(4.2f,4.5f,-25),ActivationRadius=4.2f};_polarityLever.Activated+=()=>{if(_polarityStage!=1||!_arrived||_surfaceStage<2)return;_polarityStage=2;if(_room29SideGate is not null)CreateTween().SetTrans(Tween.TransitionType.Quad).SetEase(Tween.EaseType.In).TweenProperty(_room29SideGate,"position",_room29SideGateStart+Vector3.Down*5,0.32f);};AddChild(_polarityLever);
  _room29SideGate=RoomGeometry.AddBox(this,"LeftRouteGate",new Vector3(.7f,4.2f,8),new Vector3(-9.25f,6.1f,-25),Vector3.Zero,"res://assets/textures/brushed_metal.png",rail.Darkened(.12f),.44f,.66f);_room29SideGateStart=_room29SideGate.Position;
  AddSurfaceStage("AcceleratorRun",new Vector3(8,.5f,10),new Vector3(-14,4.25f,-25),"res://resources/surfaces/accelerator.tres",new Color("58d7df"),rotation:new Vector3(0,Mathf.Pi/2,0));
  AddSurfaceStage("LowerElasticLaunch",new Vector3(18,.5f,12),new Vector3(-37,0.25f,-25),"res://resources/surfaces/super_elastic.tres",new Color("dc70a8"));
  RoomGeometry.AddBox(this,"BounceLandingDeck",new Vector3(17,.5f,24),new Vector3(-68,7.25f,-21.5f),Vector3.Zero,"res://assets/textures/diamond_plate.png",floor.Lightened(.08f),.4f,.64f);
  _polarityGateC=CourseButton("FinalCalibrationLatch",1,new Vector3(-72.8f,8.47f,-21.5f),new Vector3(5,2,3.5f));_polarityGateC.Entered+=(g,p)=>{if(p!=_p||_polarityStage!=2||_surfaceStage<4)return;g.Activate();_polarityStage=3;};AddChild(_polarityGateC);
 }
 private void Build30()
 {
  Color shell=new("777c88"),floor=new("c5cad1"),rail=new("4b515c");ShellBase(new Vector3(0,0,-105),new Vector2(34,380),34,shell);
  RoomGeometry.AddBox(this,"BankApproach",new Vector3(14,.5f,52.775f),new Vector3(0,4.25f,58.3875f),Vector3.Zero,"res://assets/textures/diamond_plate.png",floor,.42f,.62f);AddLaneRails("BankApproach",0,58.3875f,14,52.775f,rail);
  _bank=new MomentumBank3D{Name="FinalMomentumBank",Position=new Vector3(0,4.5f,36),ChargeByTime=true,ChargeDurationSeconds=12,ChargeCapacity=32,MinimumReleaseSpeed=16,ReleaseMultiplier=1,ReleaseDirection=new Vector3(0,.72f,-1),OpenApproach=true,EnableAudio=!_smoke};_bank.MomentumCaptured+=(player,speed)=>{if(player==_p&&_bank.IsFullyCharged)_bankFullyCharged=true;};_bank.MomentumReleased+=(player,speed)=>{if(player==_p)_bankReleased=true;};AddChild(_bank);
  RoomGeometry.AddBox(this,"BankCatchAndPistonDeck",new Vector3(14,.5f,74),new Vector3(0,4.25f,-40),Vector3.Zero,"res://assets/textures/diamond_plate.png",floor.Darkened(.03f),.42f,.62f);AddLaneRails("BankCatch",0,-40,14,74,rail);
  _piston=new MomentumPiston3D{Name="FinalMomentumPiston",Position=new Vector3(0,4.5f,-70),Rotation=new Vector3(Mathf.DegToRad(-60),0,0),LaunchVelocity=new Vector3(0,24,0),WindUpTicks=30,EnableAudio=!_smoke};_piston.Fired+=body=>{if(body==_p)_pistonFired=true;};AddChild(_piston);
  RoomGeometry.AddBox(this,"CannonDeck",new Vector3(14,.5f,28),new Vector3(0,4.25f,-132),Vector3.Zero,"res://assets/textures/diamond_plate.png",floor.Lightened(.04f),.42f,.62f);AddLaneRails("CannonDeck",0,-132,14,28,rail);
  _gun=new PlayerCannon3D{Name="FinalPlayerCannon",Position=new Vector3(0,4.5f,-136),LaunchVelocity=new Vector3(0,6,-22),MuzzleOffset=new Vector3(0,2,-1),ActivationRadius=5};_gun.Fired+=body=>{if(body==_p)_fired=true;};AddChild(_gun);
  ForceVolume3D lowGravity=new(){Name="FinalLowGravity",Position=new Vector3(0,13,-194),CollisionLayer=0,CollisionMask=1,Profile=GD.Load<ForceVolumeProfile>("res://resources/force_volumes/low_gravity.tres")};lowGravity.AddChild(new CollisionShape3D{Shape=new BoxShape3D{Size=new Vector3(30,24,112)}});AddChild(lowGravity);RoomGeometry.AddLowGravityMotes(this,"FinalLowGravityMotes",lowGravity.Position,new Vector3(14,11,54),132);
  AddFinalFlightGate("FinalFlightGateOne",0,new Vector3(0,11.8f,-161));AddFinalFlightGate("FinalFlightGateTwo",1,new Vector3(0,14,-191));AddFinalFlightGate("FinalFlightGateThree",2,new Vector3(0,11.8f,-221));
  int cannonIndex=0;foreach(float z in Enumerable.Range(0,42).Select(index=>Mathf.Lerp(-148f,-238f,index/41f))){float routeY=z>=-161f?Mathf.Lerp(9f,11.8f,Mathf.Clamp((-z-148f)/13f,0,1)):z>=-191f?Mathf.Lerp(11.8f,13f,(-z-161f)/30f):z>=-221f?Mathf.Lerp(13f,11.8f,(-z-191f)/30f):Mathf.Lerp(11.8f,7f,Mathf.Clamp((-z-221f)/29f,0,1));float verticalShift=Mathf.PosMod(routeY-3.8f,3.2f);if(verticalShift>1.6f)verticalShift-=3.2f;foreach(float y in Enumerable.Range(0,10).Select(index=>index*3.2f))foreach(float side in new[]{-1f,1f}){cannonIndex++;InterferenceCannon3D cannon=new(){Name=$"InterferenceCannon{cannonIndex}",Position=new Vector3(side*9.5f,y+verticalShift,z),MuzzleOffset=new Vector3(-side*2.8f,2.2f,0),ProjectileVelocity=new Vector3(-side*21,0,0),InitialDelayTicks=10+(cannonIndex*7)%180,CadenceTicks=90+(cannonIndex*13)%120,ProjectileLifetimeTicks=58,PoolSize=2,EnableAudio=!_smoke&&cannonIndex%12==0,EnableWarningLight=cannonIndex%8==0,UseBatchedDenseVisuals=true};cannon.PlayerHit+=player=>{if(player==_p)_cannonHit=true;};AddChild(cannon);_interferenceCannons.Add(cannon);}}InterferenceCannon3D.AddDenseVisualBatch(this,_interferenceCannons);
  AddCaramelAbsorber(new Vector3(14,.5f,24),new Vector3(0,4.25f,-250));RoomGeometry.AddBox(this,"FinalExitDeck",new Vector3(14,.5f,20),new Vector3(0,4.25f,-272),Vector3.Zero,"res://assets/textures/diamond_plate.png",floor.Lightened(.1f),.42f,.62f);AddLaneRails("FinalExit",0,-272,14,20,rail);
 }
 private RouteCheckpoint3D CourseButton(string name,int index,Vector3 position,Vector3 size)=>new(){Name=name,CheckpointIndex=index,Position=position,TriggerSize=size,FrameTint=RoomGeometry.SequenceButtonFrameTint,FlatFloorMarker=true,RequireFloorContact=true,AutomaticPressEnabled=true,ShowFloorButtonIndicators=true};
 private Area3D CourseArea(string name,Vector3 position,Vector3 size){Area3D area=new(){Name=name,Position=position,CollisionLayer=0,CollisionMask=1,Monitoring=true,Monitorable=false};area.AddChild(new CollisionShape3D{Shape=new BoxShape3D{Size=size}});return area;}
 private void AddSurfaceStage(string name,Vector3 size,Vector3 position,string profilePath,Color color,string texturePath="res://assets/textures/rubber_chevrons.svg",Vector3 rotation=default){SurfaceProfile profile=GD.Load<SurfaceProfile>(profilePath);StandardMaterial3D material=RoomGeometry.CreateMaterial(texturePath,color,.18f,.58f,emissionEnabled:true,emission:color.Darkened(.62f));RoomGeometry.AddBox(this,name,size,position,rotation,string.Empty,Colors.White,0,profile.Friction,surfaceProfile:profile,materialOverride:material);}
 private void AddLaneRails(string prefix,float x,float z,float width,float length,Color color){foreach(float side in new[]{-1f,1f})RoomGeometry.AddWall(this,$"{prefix}Rail{side}",new Vector3(.34f,1.35f,length),new Vector3(x+side*(width*.5f+.18f),5.05f,z),Vector3.Zero,"res://assets/textures/brushed_metal.png",color,.42f,.64f);}
 private void AddFinalFlightGate(string name,int index,Vector3 position){FlightGate3D gate=new(){Name=name,Position=position,Radius=2.35f,MinimumExitSpeed=25,SpeedGain=0,SpeedMultiplier=1,MaximumExitSpeed=40,AxialBoostOnly=true,EnableAudio=!_smoke};gate.Passed+=player=>{if(player!=_p)return;if(index==_flightGateStage){_flightGateStage++;if(_flightGateStage==_flightGates.Count)_correctRail=true;}};AddChild(gate);_flightGates.Add(gate);}
 private bool FinalCannonsFillWalls()=>_interferenceCannons.Count==840&&_interferenceCannons.Select(cannon=>cannon.ScheduledFirstFireTick).Distinct().Count()>=100&&_interferenceCannons.All(cannon=>cannon.UseBatchedDenseVisuals)&&InterferenceCannon3D.HasDenseVisualBatch(this,840)&&_interferenceCannons.Min(cannon=>cannon.Position.Y)<=1.61f&&_interferenceCannons.Max(cannon=>cannon.Position.Y)>=27.19f&&_interferenceCannons.Min(cannon=>cannon.Position.Z)<=-237.99f&&_interferenceCannons.Max(cannon=>cannon.Position.Z)>=-148.01f;
 private void AddCaramelAbsorber(Vector3 size,Vector3 position){SurfaceProfile profile=GD.Load<SurfaceProfile>("res://resources/surfaces/absorbing.tres");ShaderMaterial material=(ShaderMaterial)GD.Load<ShaderMaterial>("res://resources/materials/sticky_caramel.tres").Duplicate();RoomGeometry.AddBox(this,"CaramelAbsorbingLanding",size,position,Vector3.Zero,string.Empty,Colors.White,0,profile.Friction,surfaceProfile:profile,materialOverride:material);}
private void AddCounterweight(Vector3 p){_counterweight=new Node3D{Name="Counterweight",Position=p};_counterStart=p;AddChild(_counterweight);RoomGeometry.AddVisualBox(_counterweight,"Mass",new Vector3(5,7,5),Vector3.Zero,Vector3.Zero,"res://assets/textures/copper_rivets.svg",new Color("6c5d48"),.45f,.58f);_counterweightCableTop=44.8f;float bottom=p.Y+3.5f;_counterweightCableBaseLength=_counterweightCableTop-bottom;_counterweightCable=RoomGeometry.AddVisualBox(this,"Cable",new Vector3(.22f,_counterweightCableBaseLength,.22f),new Vector3(p.X,(bottom+_counterweightCableTop)*.5f,p.Z),Vector3.Zero,"res://assets/textures/brushed_metal.png",new Color("2d3030"),.45f,.55f);StandardMaterial3D pulley=RoomGeometry.CreateMaterial("res://assets/textures/copper_rivets.svg",new Color("8d7451"),.45f,.55f);RoomGeometry.AddCylinder(this,"Pulley",new Vector3(p.X,45.5f,p.Z),new Vector3(Mathf.Pi/2,0,0),2.2f,.7f,pulley);}
private void UpdateCounterweightCable(){if(_counterweight is null||_counterweightCable is null)return;float bottom=_counterweight.Position.Y+3.5f;float length=Mathf.Max(.2f,_counterweightCableTop-bottom);_counterweightCable.Position=new Vector3(_counterweight.Position.X,(bottom+_counterweightCableTop)*.5f,_counterweight.Position.Z);_counterweightCable.Scale=new Vector3(1,length/_counterweightCableBaseLength,1);}
 private void BuildGoal(){Vector3 pos=RoomNumber switch{27=>new Vector3(8,5.35f,-62),28=>new Vector3(6.5f,25.35f,-49),29=>new Vector3(-75,8.35f,-25),30=>new Vector3(0,5.35f,-281),_=>new Vector3(0,5.35f,-48)};Area3D g=new(){Name="GoalCup",Position=pos,CollisionLayer=0,CollisionMask=1,Monitoring=true};g.AddChild(new CollisionShape3D{Shape=new CylinderShape3D{Radius=2.2f,Height=3}});g.BodyEntered+=body=>{if(body is PlayerBall&&Requirements()){if(RoomNumber==29&&!_railTouchedAfterStart)MarkAdvancementCondition("smooth-operator");if(RoomNumber==30&&_correctRail&&!_cannonHit)MarkAdvancementCondition("final-inspection");CompleteRoom();}};AddChild(g);Vector3? outward=RoomNumber switch{27=>Vector3.Right,29=>Vector3.Left,_=>null};ExitDoor3D door=RoomGeometry.AddGoalExitDoor(this,pos,outward);if((RoomNumber is 29 or 30)&&door.GetNodeOrNull<OmniLight3D>("DoorFillLight") is OmniLight3D light){light.LightColor=Colors.White;light.LightEnergy=.55f;}}
 private void RunHitSurvivalSmoke(){if(RoomNumber!=30){Fail("hit-survival smoke was requested outside Room 30");return;}_bankReleased=_pistonFired=_fired=_absorbed=_correctRail=_cannonHit=true;_flightGateStage=_flightGates.Count;GetNode<Area3D>("GoalCup").EmitSignal(Area3D.SignalName.BodyEntered,_p);if((!IsComplete&&!IsExitTraversalPending)||CompletedAdvancementIds.Contains("final-inspection")){Fail($"surviving a cannon hit did not complete normally or incorrectly awarded Final Inspection: complete={IsComplete||IsExitTraversalPending}, awarded={CompletedAdvancementIds.Contains("final-inspection")}");return;}GD.Print($"ROOM30_HIT_SURVIVAL_PASS: all {_interferenceCannons.Count} cannons remain optional hazards; a surviving hit denies Final Inspection but does not block completion.");Finish(0);}
 private void Fail(string m){GD.PushError($"ROOM{RoomNumber:00}_SOLUTION_FAIL: {m}");Finish(1);}private async void Finish(int c){if(_finish)return;_finish=true;_trace=null;await ToSignal(GetTree(),SceneTree.SignalName.ProcessFrame);await ToSignal(GetTree(),SceneTree.SignalName.ProcessFrame);GetTree().Quit(c);}
}
